.TH TINT 6 "June 23, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tint \- clone of the original tint
.SH SYNOPSIS
.B tint
.RI [ -h ]
.RI [ -l\  level ]
.RI [ -n ]
.RI [ -d ]
.RI [ -b\  char ]
.SH DESCRIPTION
This manual page documents briefly the
.B tint
clone. As with all games (and especially with tint), you have to play it,
not read about it.
.SH OPTIONS
A summary of options is included below.
For a complete description, see the NOTES file in /usr/share/doc/tint.
.TP
.B \-h
Show summary of options.
.TP
.B \-l <level>
Specify the starting level (1-9). The higher the level you're starting from,
the faster you'll earn points.
.TP
.B \-n
Draw next shape. When the next shape is drawn, you might find the game to be
easier, but it will be slower to earn points.
.TP
.B \-d
Draw dotted lines.
.TP
.B \-b <char>
Use the specified character (instead of spaces) to draw blocks.
.SH AUTHOR
This manual page was written by Abraham van der Merwe <abz@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
